// react-vite/src/App.tsx
import { useRef, useState } from 'react';
import { Editor, type CutforgeCommands } from '@cutforge/editor';
import '@cutforge/editor/style.css';

export default function App() {
  const editor = useRef<CutforgeCommands>(null);
  const [status, setStatus] = useState('Drop a video on the editor, then export.');

  // Driving the export from your own UI: `export()` resolves with the Blob and does
  // not download it, so what happens next is up to you (this example downloads it).
  async function exportFromHost() {
    const result = await editor.current?.export({ format: 'mp4' });
    if (!result) return;
    const a = document.createElement('a');
    a.href = URL.createObjectURL(result.blob);
    a.download = result.filename;
    a.click();
    URL.revokeObjectURL(a.href);
  }

  return (
    <div style={{ display: 'grid', gridTemplateRows: 'auto 1fr', height: '100%' }}>
      <header style={{ display: 'flex', gap: 12, alignItems: 'center', padding: 8, font: '14px system-ui' }}>
        <button onClick={exportFromHost}>Export MP4 from the host app</button>
        <span>{status}</span>
      </header>
      <Editor
        ref={editor}
        // No key: watermarked demo (60 s / 720p exports). Put your key in .env to lift it.
        license={import.meta.env.VITE_CUTFORGE_LICENSE}
        // Fires after every export, from the editor's own Export button (which also
        // downloads the file) or from export(). Upload the Blob to your storage here.
        onExportComplete={({ blob, filename }) =>
          setStatus(`Exported ${filename} (${(blob.size / 1e6).toFixed(1)} MB), rendered on this machine.`)
        }
        style={{ minHeight: 0 }}
      />
    </div>
  );
}

// vue/src/App.vue
<script setup>
import { onBeforeUnmount, onMounted, ref } from 'vue';
import { createEditor } from '@cutforge/editor';
import '@cutforge/editor/style.css';

// Cutforge renders its own UI (with React, bundled as a peer dependency), so from Vue
// you mount it into an element and destroy it when the component goes away.
const host = ref(null);
const status = ref('Drop a video on the editor, then export.');
let editor;

onMounted(() => {
  editor = createEditor(host.value, {
    // No key: watermarked demo (60 s / 720p exports). Put your key in .env to lift it.
    license: import.meta.env.VITE_CUTFORGE_LICENSE,
  });
  // Upload the Blob to your own storage here.
  editor.on('export-complete', ({ blob, filename }) => {
    status.value = `Exported ${filename} (${(blob.size / 1e6).toFixed(1)} MB), rendered on this machine.`;
  });
});

onBeforeUnmount(() => editor?.destroy());
</script>

<template>
  <div class="page">
    <p class="status">{{ status }}</p>
    <div ref="host" class="editor"></div>
  </div>
</template>

<style scoped>
.page { display: grid; grid-template-rows: auto 1fr; height: 100%; }
.status { margin: 0; padding: 8px; font: 14px system-ui; }
.editor { min-height: 0; }
</style>
